name: 'Pull Request Naming Checker'
description: 'Check if pull request title matches any of defined formats'
author: 'infomiho'
inputs: 
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  configuration-path:
    description: 'The path for the naming configurations'
    default: '.github/pr-naming.yml'
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
